-- Stage 1: agent loop fields + NEEDS_INFO / AGENT_RUNNING statuses

ALTER TYPE "TaskStatus" ADD VALUE IF NOT EXISTS 'AGENT_RUNNING';
ALTER TYPE "TaskStatus" ADD VALUE IF NOT EXISTS 'NEEDS_INFO';

ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "businessSummary" JSONB;
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "logoUrl" TEXT;
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "visionMatches" JSONB;

ALTER TABLE "UploadedImage" ADD COLUMN IF NOT EXISTS "matchedProduct" TEXT;
ALTER TABLE "UploadedImage" ADD COLUMN IF NOT EXISTS "matchConfidence" DOUBLE PRECISION;
ALTER TABLE "UploadedImage" ADD COLUMN IF NOT EXISTS "description" TEXT;

ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "businessSummary" JSONB;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "logoUrl" TEXT;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "productSummary" JSONB;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "productImageUrl" TEXT;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "statusLabel" TEXT;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "pendingQuestion" TEXT;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "agentState" JSONB;
